version: '3.3'

services:
#  wanhao:
#    image: octoprint/octoprint
#    restart: unless-stopped
#    devices:
#      - /dev/ttyUSB1:/dev/ttyUSB0
#      - /dev/video0:/dev/video0
#    volumes:
#     - ./wanhao:/octoprint
#    environment:
#      - CAMERA_DEV=/dev/video0
#      - ENABLE_MJPG_STREAMER=true
#      - MJPG_STREAMER_INPUT='-n -r 1280x720'
#    networks:
#      - traefik_proxy
#    ports:
#      - "5001:80"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.wanhao.entrypoints=https"
#      - "traefik.http.routers.wanhao.rule=(Host(`wanhao.josh.services`))"
#      - "traefik.http.routers.wanhao.tls.certresolver=le"
#      - "traefik.docker.network=traefik_proxy"

  delta:
    image: octoprint/octoprint
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    volumes:
     - ./delta:/octoprint
    environment:
      - CAMERA_DEV=/dev/video0
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT='-n -r 1280x720'
    networks:
      - traefik_proxy
    ports:
      - "5000:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.delta.entrypoints=https"
      - "traefik.http.routers.delta.rule=(Host(`delta.josh.services`))"
      - "traefik.http.routers.delta.tls.certresolver=le"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external: true

  ####
  # uncomment if you wish to edit the configuration files of octoprint
  # refer to docs on configuration editing for more information
  ####

  #config-editor:
  #  image: linuxserver/code-server
  #  ports:
  #    - 8443:8443
  #  depends_on:
  #    - octoprint
  #  restart: unless-stopped
  #  environment:
  #    - PUID=0
  #    - GUID=0
  #    - TZ=America/Chicago
  #  volumes:
  #    - octoprint:/octoprint
